/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_article {
    constructor() {
        this.id = undefined;
        this.title = undefined;
        this.uid = undefined;
        this.createTime = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setCreateTime(createTime) {
        this.createTime = createTime;
    }

    getCreateTime() {
        return this.createTime;
    }
}

t_article.className = 't_article';

export {t_article}